dist: xenial # for python 3.7
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install: ./go setup
script: ./go check && ./go test
addons:
  apt:
    packages:
    - pandoc
jobs:
  include:
    - stage: check release-readiness
      script: ./go test-setuptools
      install: skip # no need for venv and dev dependencies here
    - stage: check release-readiness
      script: ./go test-docker-build
      install: skip # no need for venv and dev dependencies here
