language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
install: ./go setup
script: ./go check && ./go test
addons:
  apt:
    packages:
    - pandoc
jobs:
  include:
    - stage: check release-readiness
      name: test setuptools
      script: ./go test-setuptools
      install: skip # no need for venv and dev dependencies here
      language: minimal # we are running docker so no need for installing python here
    - stage: check release-readiness
      name: test docker build
      script: ./go test-docker-build
      install: skip # no need for venv and dev dependencies here
      language: minimal # we are running docker so no need for installing python here
