name: Dependabot auto-merge
on:
  check_suite:
    types: [ completed ]
jobs:
  dependabot:
    runs-on: ubuntu-latest
#    if: github.base_ref != null # pull requests only
    if: github.actor == 'dependabot[bot]'
    steps:
      -  name: "Say hello"
         run: echo "Actor $ACTOR, event $EVENT"
         env:
           ACTOR: ${{github.actor}}
           EVENT: ${{toJSON(github.event)}}

#      - name: Enable auto-merge for Dependabot PRs
#        run: gh pr merge --auto --merge "$PR_URL"
#        env:
#          PR_URL: ${{github.event.pull_request.html_url}}
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}